# Generated by Django 3.0.3 on 2020-10-01 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 9, 32, 3, 187502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 9, 32, 3, 187143, tzinfo=utc)),
        ),
    ]
