# Generated by Django 3.0.3 on 2020-10-06 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201001_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 15, 57, 28, 89709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 15, 57, 28, 89348, tzinfo=utc)),
        ),
    ]
